### ISSUE TITLE
Coding guidelines are not followed

### ISSUE THREAD

**Issue by peske** [eduvpn/eduvpn-common#1]
Although not being a critical, functional problem, not following coding guidelines causes problem on a long run, when the code should be maintained, especially when a new developers are included. For this reason I **strongly** suggest taking much more care about that. In the current code almost all the guidelines are broken.

Let me first share few authoritative resources for learning more about the guidelines:

- https://go.dev/doc/effective_go
- https://google.github.io/styleguide/go/guide
- https://go.dev/doc/comment

Also, I would strongly suggest using linters, formaters, and for developers who are new in the language some IDE that helps with that. For example, JetBrains GoLand will report hundreds problems with the current code. Similar probably stands for Visual Studio Code with an appropriate plugin.

Current code contains dozens of guideline problems in any file. Let me share just few:

https://github.com/eduvpn/eduvpn-common/blob/6229767a7d5b0d3cf3125f2e9da0ca0e66ada814/client/client_test.go#L103

Test functions should start with `Test` followed by method name. For example, if we want to test function called `MyFunction`, we will create test `TestMyFunction`. Snake case (like `test_connect_oauth_parameter`) is never used in Go, not for function names, nor for anything else. Camel case should be used instead. Camel case is often used in the current code.

https://github.com/eduvpn/eduvpn-common/blob/6229767a7d5b0d3cf3125f2e9da0ca0e66ada814/client/client_test.go#L309

Variable names should not ever collide with already used names. Here we have variable `oauth` that collides with package name `oauth`.

Documentation comments almost never follow the guidelines https://go.dev/doc/comment

These are only few examples that often happen.

**Comment by jwijenbergh** [comment]
Thanks! I am using [golangci-lint](https://github.com/golangci/golangci-lint) for the CI linting. I will need to figure out how to add a style guide to it and adhere with it + document that we use it.

**Comment by jwijenbergh** [comment]
Improvements made in 8be555e5f91c6069c3d51cb014f1849fd182b1dc

**Comment by jwijenbergh** [comment]
If coding guidelines are not more closely followed then you can re-open. For now, there should be a big improvement
