### ISSUE TITLE
Determine if more from expiry can be implemented

### ISSUE THREAD

**Issue by efef** [eduvpn/eduvpn-common#10]
A new algorithme was chosen when to show the button. A diff is available here:

https://github.com/eduvpn/documentation/commit/cdf4d054f7652d74e4192494e8bb0e21040e46ac

**Comment by jwijenbergh** [comment]
The button change is implemented in https://github.com/eduvpn/eduvpn-common/commit/f106485d6a757e92949e0c0da6b68385879e4623 (removing the 75% requirement).

We would need to figure out if it makes sense to also implement the os notification timestamps and the countdown timer times in `eduvpn-common`. Right now it's just return a boolean whether or not the button should be shown. I will rename this issue to track the other things

**Comment by jwijenbergh** [comment]
Maybe it makes sense to return the time that things should be shown. E.g. a function like `GetExpiryTimes` would return json like:

Times 0-5 are placeholder for unix timestamps:
```json
"button_time": 0,
"countdown_time": 1,
"notification_times": [2, 3, 4, 5],
```

Clients can then schedule according to these times

**Comment by jwijenbergh** [comment]
> Maybe it makes sense to return the time that things should be shown. E.g. a function like `GetExpiryTimes` would return json like:
> 
> Times 0-5 are placeholder for unix timestamps:
> 
> ```json
> "button_time": 0,
> "countdown_time": 1,
> "notification_times": [2, 3, 4, 5],
> ```
> 
> Clients can then schedule according to these times

implemented in the v2 branch
