### ISSUE TITLE
V2: Combine discovery functions

### ISSUE THREAD

**Issue by jwijenbergh** [eduvpn/eduvpn-common#18]
Should DiscoOrganizations and DiscoServers be combined? Why are there 2 functions?

Clients should almost always fetch them together, no?

**Comment by rozmansi** [comment]
Pre eduvpn-common eduVPN client for Windows: when started, it used server discovery to rearrange no-longer available Institute Access servers to Own servers and vice versa. Organization discovery is not needed for this and was triggered only if user clicks to add a new IA server or Secure Internet.

eduvpn-common based eduVPN client for Windows: when IA servers or Secure Internet is detected in old config, the server discovery is triggered. When SI is detected in old config, the organization discovery is triggered next. So, in case there were only IA servers and no SI, only the server discovery is done on startup.

**Comment by jwijenbergh** [comment]
right then I think we can close this due to this optimization?
