### ISSUE TITLE
V2: Should discovery have a `local` argument to force the cache?

### ISSUE THREAD

**Issue by jwijenbergh** [eduvpn/eduvpn-common#19]
Problem:

getting disco servers/organizations can be slow due to the discovery server or the users network being slow. Even though we have a timeout and a cookie, it might be nice to introduce a `local`/`cache` argument to the functions

If non-zero/true this means that only the cached copy is returned. Clients can thus first call the functions with true and then asynchronously call it with false to get the most up to date copy.

This is right now the most problematic on startup where clients have no discovery cache filled

**Comment by rozmansi** [comment]
The discovery cache is initially prefilled at compile time, right? So, even on initial startup eduvpn-common should have discovery cached.

**Comment by jwijenbergh** [comment]
> The discovery cache is initially prefilled at compile time, right? So, even on initial startup eduvpn-common should have discovery cached.

This is true but it still tries to get it from the network (if they should be updated as deemed by the common lib). If you have a slow connection it only falls back to the cache after the HTTP timeout, which may be a problem?

**Comment by jwijenbergh** [comment]
Didn't get a lot of +1s from the team

**Comment by jwijenbergh** [comment]
discussed with roop

**Comment by jwijenbergh** [comment]
moved to https://codeberg.org/eduVPN/eduvpn-common/issues/19
