### ISSUE TITLE
V2: Should CurrentServer be returned on GotConfig?

### ISSUE THREAD

**Issue by jwijenbergh** [eduvpn/eduvpn-common#20]
Should the current server be sent as data to the GotConfig state?

Upside: 
- Not as much calls needed to currentserver anymore
- The FSM becomes the best single source of truth for the current state

Downside:
- Performance maybe? As clients that not want to use this data then have extra (very small though) overhead

**Comment by rozmansi** [comment]
This would look awkward then: the GotConfig callback data is not Config, but Server.
Unless GotConfig state callback would provide data for Config, Server and ExpiryTimes together?

Initially, I was attempting to implement eduVPN client for Windows trying to use callback as much as possible to drive the GUI. However, the callbacks provide only essential and absolutely necessary data. But nobody is stopping you from calling `CurrentServer()` or `ExpiryTimes()` in the callback handler if you need this data. So, performance-wise the current solution seems best.

**Comment by jwijenbergh** [comment]
> GotConfig state callback would provide data for Config, Server and ExpiryTimes together
Possible indeed

It is possible that we should utilize callback data more. E.g. NoServer should maybe also contain the server list?

**Comment by rozmansi** [comment]
True. Callbacks are mandatory (AskLocation, OAuthStarted, AskProfile) not optional. If we decide to go this way, everything should be migrated to the callbacks making only those API functions that represent user-induced action remain.

Otherwise, we get some half-baked solution.

**Comment by jwijenbergh** [comment]
I think this is not a good improvement (title). 

> If we decide to go this way, everything should be migrated to the callbacks making only those API functions that represent user-induced action remain.

Maybe we could reconsider this later, but I think that only having the mandatory callbacks have data in them makes some sense
