### ISSUE TITLE
Persist internal state regularly

### ISSUE THREAD

**Issue by rozmansi** [eduvpn/eduvpn-common#22]
Unregistering engine saves the internal state (user settings). Unregister is called when client is terminating. However, client might be terminated by force. We had this problem with Windows client: manually installing newer version of the client kills all running client processes and user changes are lost.

If eduvpn-common doesn't implement in-between saves, we will experience this issue again.

In .NET this was fixed by introducing a timer which is reset to 5 seconds on each settings change. When timer triggers, settings are saved.

See: https://github.com/Amebis/eduVPN/issues/222

**Comment by jwijenbergh** [comment]
In V1 I save the configuration after adding servers, removing servers, getting a configuration and of course deregister.

In V2 it's only in deregister. We can either do periodically saving in the background or determine that the V1 approach was enough.

**Comment by rozmansi** [comment]
V1 approach is enough, provided we don't miss any change of the user configuration.

**Comment by jwijenbergh** [comment]
Fixed in v2 add4b39805a38e92068636e47019d9234d62e613
