### ISSUE TITLE
Suspicious error handling

### ISSUE THREAD

**Issue by peske** [eduvpn/eduvpn-common#6]
I have to tell that I'm not absolutely sure about this issue, just sharing the first intuition. I will have to take more detailed look.

It looks to me that error handling is convoluted because a lot of error wrappings that happen throughout the code. Catching error, than wrap it and return the wrapped, than maybe wrap it again, etc. Again, will have to take a deeper look into this problem.

Another thing that bit scares me is the fact that errors are kinda propagated to UI. Yes, I agree that it is reasonable to have a meaningful error message in the UI. But sending a whole error structure bit scares me cause it looks like passing error handling upstream to UI.

https://github.com/eduvpn/eduvpn-common/blob/6229767a7d5b0d3cf3125f2e9da0ca0e66ada814/exports/error.h#L11

Not sure what's the reason for wrapping, but if it is to get the stack trace - this already exists in `errors` package out-of-the-box.

When it comes to passing error messages to UI, I would rather go with error codes. This way UI can do some translation / localization...

Again, will have to take a deeper look to have more articulate suggestion.

**Comment by jwijenbergh** [comment]
I do agree with you that error codes are better. But that means that the error codes between the wrappers (e.g. the python code) and the go code always need to be in sync. Furthermore, how would I define error codes for built in errors? The main problem I have right now is that built in go errors (from the standard library or some other dependency) is not always a clear error that can be presented in the UI. The "errorMessage" that I define everywhere tries to be a clear error of what went wrong. I agree that localization is a big part that still needs some thought.

The custom wrapper code is mainly used so that I can have my own custom Traceback format, additionally, I use different error levels for wrapping. Such that if an error is indicated as "INFO" this means that the wrapped error also becomes an Info error (it inherits the same error level). This is useful to present different category of errors in the UI.

**Comment by peske** [comment]
There are several issues that I'm trying to understand when it comes to errors, and I will write separate comments here. Let's start from the first one: how and why errors propagate to UI. Obviously user needs to get some friendly message about the error - I agree with that. But why sending traceback to UI?

When it comes to sending level to UI, I kinda understand your intent. Some errors may require just "retry", while others cannot be solved easily... But I don't see that in the current code. The only error with info level is currently:

https://github.com/eduvpn/eduvpn-common/blob/1a6e6d024ee4fb96b433da6eac702ddde9296747/internal/oauth/oauth.go#L447

And as far as I can see from the code this can only happen if the cancellation is initiated from the UI, so there's no need for notifying the user that "user cancelled OAuth".

I'm not sure in which format error should be sent to UI to be displayed (error code or error message), but I'm pretty sure that it should not include traceback, nor level.

**Comment by peske** [comment]
Another thing when it comes to error levels: this feature is not used in the code at all. The only place where the error level is assigned is already mentioned in my comment above. I don't see that other levels (warning and fatal) are assigned anywhere. In other words, error levels are implemented because of some future expectations, not actual current need. This breaks one of the core principles of software development in general, especially in Golang where simplicity is priority. This principle states:

> Maintainable code avoids unnecessary coupling and doesn’t include features that are not used.

Please check https://google.github.io/styleguide/go/guide#maintainability.

**Comment by peske** [comment]
In case when different handling is needed depending on the severity / type of the error, it is better to go with different error types than levels, as in the following pseudo code:

```go
	switch et := err.(type) {
	case UserCancelledError:
		// Handle not too dangerous error
	default:
		// Handle other errors
	}
```

Such code is much more readable because clearly shows the intention. It's immediately obvious why some errors are less dangerous then others. With levels on the other side, person that looks at the code may not understood why some errors have level `info` while others `fatal`.

At the end of the day, it is not coincidence that usage of levels with errors is rare.

**Comment by peske** [comment]
Just let me explain why I am insisting on this: error handling is simply too convoluted without any reason. I've had a though time understanding what is happening there, so chances are that other devs would also have problems understanding that.

**Comment by jwijenbergh** [comment]
I agree that is much too complex, but most go libraries do not have to deal with interfacing with other languages :)

**Comment by jwijenbergh** [comment]
Error codes are the best solution to this problem, but also hard to realize. Do you have any idea how we could use the same error codes between python and go with a low maintenance burden to keep them in sync? See the following for some history about error codes in the library https://github.com/stevenwdv/eduvpn-common/blob/main/verify.go
