### ISSUE TITLE
add connection error (Ubuntu 24.04.1)

### ISSUE THREAD

**Issue by lcscs12345** [eduvpn/eduvpn-common#71]
Hi,

Thanks for maintaining eduVPN. I have installed eduVPN using `apt` and ran into this connection issue. 
```
$ eduvpn-cli -v
eduVPN CLI version: 4.4.0 with eduvpn-common version: 2.1.0

$ eduvpn-cli connect -n1
2024-09-28 08:22:51,892 - MainThread - ERROR - eduvpn.nm - nm.py:917 - add connection error: g-dbus-error-quark: Message recipient disconnected from message bus without replying (4)
```

Edit: It works in commandline when I manually import the configuration as https://github.com/eduvpn/eduvpn-common/issues/61 and bring up the connection afterwards. However, the eduVPN GUI didn't work before and after a reboot. It showed
```
The following error was reported: Failed to connect to server: 'https://eduvpn.otago.ac.nz/'. The cause of the error is: Timeout reached contacting URL: 'https://eduvpn.otago.ac.nz/.well-known/vpn-user-portal'.
```

**Comment by jwijenbergh** [comment]
Hmmm that error just indicates you have no internet?

**Comment by lcscs12345** [comment]
Thanks @jwijenbergh. I have no issues with internet.

**Comment by jwijenbergh** [comment]
Can you make a video of using the GUI? And send me a complete debug log (client -d flag). You can do so through eduvpn-support@lists.geant.org if you prefer not to have it public

**Comment by jwijenbergh** [comment]
moved to https://codeberg.org/eduVPN/eduvpn-common/issues/71
