### ISSUE TITLE
Doesn’t work on musl-based systems (e.g. Alpine Linux)

### ISSUE THREAD

**Issue by jirutka** [eduvpn/eduvpn-common#75]
`libeduvpn_common.so` segfaults when built against musl libc on a musl-based system, such as Alpine Linux, because Go doesn’t produce correct shared libraries – see https://github.com/golang/go/issues/54805#issuecomment-1253972041.

I don’t understand why you implemented this library in a language that is not designed for shared libraries at all…

**Comment by jwijenbergh** [comment]
Simple: Go is a language that has a good tradeoff between simplicity, performance and portability. On top of that, the standard library allows me to write a library like this without a million dependencies.

I'm not sure what you expect me to do in this issue, yes support will be good but this is something that has to be fixed on the Go side.

**Comment by Johnnynator** [comment]
I don't think there is any reason to blame to someone for using go for dynamic libs, go makes a bad job at documenting the shortcomings.

@jirutka You just need some patch for go to fix their argv brokenness (Something like https://go-review.googlesource.com/c/go/+/610837 ), after that just have some small wrapper scripts that LD_PRELOADS eduvpn_common, not the nicest way, but it does work.

![EduVPN running with musl libc](https://github.com/user-attachments/assets/8be28455-6e5e-482c-af7a-ccc2a80e59a6)

**Comment by hyperiris** [comment]
Yes, golang works well on server side and makes a lot of successed products.
BUT, golang on client side is crappy. using go on client side and hope it "cross platform" is a joke.
In my career, I saw many fail on it, for example: cgo working in 2KB stack, no c-shared on target platfrom, can't work with musl, and sometimes creates thounds of thread on windows platform, the runtime defaults read HTTP_PROXY and HTTPS_PROXY env so cause hard to diagnosis bug and many many to remember to makes me PTSD.
Finally and last, the ultimate problem is: issues of go won't be fix for many years, especially the case of community already supply the patch or fix, and google go team refuse to review and accept them, its "low priority","not planned","not important" or just shelve them.

**Comment by proycon** [comment]
I just tried to package this for Alpine (https://gitlab.alpinelinux.org/proycon/aports/-/commits/eduvpn) and ran into the same issue with Go (...and then I found this issue too.. seeing I'm not the first to try). 

@jirutka Is that patch something we can apply to golang in Alpine? (as long as golang upstream isn't responsive)

**Comment by proycon** [comment]
I gave it a try but then one of golang's test fails:

```
--- FAIL: TestMachOBuildVersion (1.76s)                                          
    link_test.go:377: [/home/proycon/projects/sxmo/aports/community/go/src/go/bin
/go build -ldflags=-linkmode=internal -o /tmp/TestMachOBuildVersion1880507020/001
/main /tmp/TestMachOBuildVersion1880507020/001/main.go]: exit status 1:          
        # runtime                                                                
        ../../runtime/runtime1.go:122:23: undefined: _O_RDONLY                   
FAIL                                    
FAIL    cmd/link        8.939s             
```

**Comment by jirutka** [comment]
> I just tried to package this for Alpine 

I already have a fully working aport, but it depends on the following patch for go.

> @jirutka Is that patch something we can apply to golang in Alpine?

Yes, but the maintainer doesn’t want to merge it – [!74750](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/74750). :/ And about the upstream, it’s exactly the situation described by @hyperiris.

Since we decided to use a different solution than eduVPN, it’s not a high priority to me so I’m not urging it. However, it may help if you drop a comment to [!74750](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/74750).

**Comment by proycon** [comment]
On Fri Nov 29, 2024 at 12:14 AM CET, Jakub Jirutka wrote:
> I already have a fully working aport, but it depends on the following patch for go.

Ok! Good to know.

> > @jirutka Is that patch something we can apply to golang in Alpine?
>
> Yes, but the maintainer doesn’t want to merge it –
> [!74750](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/74750).
> :/ And about the upstream, it’s exactly the situation described by
> @hyperiris.
>
> Since we decided to use a different solution than eduVPN, it’s not a
> high priority to me so I’m not urging it. However, it may help if you
> drop a comment to
> [!74750](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/74750).

Right! Done! Let's hope that helps.
